### ISSUE TITLE
Color Management Exposure doesn't fall back to default value

### ISSUE THREAD

**Issue by pdesopo** [PhysicalAddons/physical-starlight-and-atmosphere#8]
**Describe the bug**
After turning Atmosphere on and then off, Exposure value is still -6

**General information**
- Blender version: 2.83 - 2.9
- Engine: Evee & Cycles
- Operating System: Windows 10

**To Reproduce**
The default value for the exposure under color management is 0. After turning Atmosphere on it goes to -6 but then switching Atmosphere off it stays on -6

**Comment by karlisup** [comment]
Hi, @pdesopo,
Sorry that it took so long to respond. The [discussion](https://blenderartists.org/t/physical-starlight-and-atmosphere-addon-for-2-8-v1-2/1185314/413), clearly shows that this currently is the very disturbing bug that affects a lot of the users and breaks a lot of workflows.

We had just a discussion with @martinsh and came to the decision to introduce **a bugfix** that will reset `exposure` to 0 when the addon is disabled. But in the next release, it will be fixed by introducing preset system which will allow to chose between physical (on the realistic physics-based atmosphere)  or non-physical presets.

Thank you for your patience.

**Comment by karlisup** [comment]
The bug has been fixed and a new version (1.2.1) has been uploaded both to BlenderMarket and Gumroad.

**Comment by febaac** [comment]
It is not working, at least in blender 2.83 / 2.83.1 in Linux Mint

**Comment by karlisup** [comment]
My apologies, 
As @ogierm pointed out in the [issue](https://github.com/PhysicalAddons/physical-starlight-and-atmosphere/issues/18), wrapping folder was missing. I updated the structure and tested in multiple Blender versions and now it's uploaded in Gumroad & BlenderMarket. Currently working on continuous integration to issues related to testing and releasing.

**Comment by djgw** [comment]
> The bug has been fixed and a new version (1.2.1) has been uploaded both to BlenderMarket and Gumroad.

Hi @karlisup - thanks for responding to reports about this bug. Unfortuately for me, the update doesn't appear to have fixed the earlier problems.  On my system, exposure remains at -6 regardless of whether Atmosphere is toggled on or off.  I downloaded your update today so must have the latest...

Also the same exposure problems I experienced in 1.2 appear to be the case with 1.2.1

After uninstalling 1.2 deleting the leftover Sun, saving my scene, resetting exposure in Colour Management to 0 and restarting, I installed 1.2.1 and switched on the Atmosphere toggle.  I've reset all settings to default.  Enabling Atmosphere sets exposure back to -6 which I presume is required as a default setting.  

At 3pm in the day (with appropriate Azimuth and Elevation settings) the scene renders very dark in Cycles and the sky is black.  Please see the attached Cycles render.  The same scene rendered in Eevee is better exposed.  However performing an Eevee viewport render fails with a mostly black image. (please refer to attached images)
![Cycles Render](https://user-images.githubusercontent.com/3997135/86248452-819f7180-bbe0-11ea-82c4-ca8d26f33816.jpg)
![Eviee Render](https://user-images.githubusercontent.com/3997135/86248487-8c5a0680-bbe0-11ea-9928-1578ec679527.jpg)
![Eviee Viewport Render](https://user-images.githubusercontent.com/3997135/86248522-967c0500-bbe0-11ea-9fa6-fa0c774d560a.jpg)

I'm not sure if this plugin is meant to be compatible with lighting - but with default settings as above it doesn't appear to be.  With exposure set to -6, any lighting added to the scene is sucked away. In the Eevee image at 19:00 with a 200W Lamp, light is barely visible.  Should Colour Management exposure be manually changed in this case? ![Evee 1900 with 200W Lamp](https://user-images.githubusercontent.com/3997135/86248557-a267c700-bbe0-11ea-98a8-909ffabda5ef.jpg)

I am new to Blender so may be missing some fundamental knowledge about the use of your software.  I have scoured the documentation without any further insights - please advise how I might utilise it correctly.

Thanks in advance!

**Comment by karlisup** [comment]
Hi @djgw,
Thank you for taking the time and explaining the issue you are having in detail.  Regarding the wrong exposure during the rendering, there is already a task about that [here](https://github.com/PhysicalAddons/physical-starlight-and-atmosphere/issues/11). I'll take look at it as soon as possible and you can follow up on the progress there.

> exposure remains at -6 regardless of whether Atmosphere is toggled on or off

This should be fixed with that small bug-fix I introduced few days ago. Is it still the same now? Anyone else having the same 
issue?

**Comment by djgw** [comment]
Hi @karlisup,
> This should be fixed with that small bug-fix I introduced few days ago. Is it still the same now?
From my extensive testing this is not fixed.  Exposure remains at -6 after disabling Atmosphere.  And the Sun object is not deleted - which is not really a problem as far as I'm concerned.   

I'm happy to do further testing for you to try to troubleshoot this issue.

My main concern is the exposure issues described earlier.   I'll follow the task you've linked and keep in touch with progress. In the meantime I must use 1.1 as your 1.2 build does not provide reliable results.

**Comment by karlisup** [comment]
Hi! The exposure bug is fixed in v1.2.2. Let us reopen the issue if any other exposure issues reoccur. Thank you for your patience!
